repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate

