name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install labelshift module
      run: |
        python -m pip install .
    - name: Check code with flake8
      run: |
        flake8
    - name: Check docstring coverage with interrogate
      run: |
        interrogate
    - name: Check whether black has been used
      run: |
        black --check tests
        black --check labelshift
    - name: Check types with pytype
      run: |
        pytype labelshift
        # pytype tests
    - name: Test with pytest
      run: |
        python -m pytest

